# Generated by Django 5.0.6 on 2024-06-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_type', '0002_businesstype_kpi'),
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='kpi',
            field=models.ManyToManyField(related_name='business_types', to='kpi.kpi'),
        ),
    ]
