# Generated by Django 5.0.6 on 2024-06-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_type', '0003_alter_businesstype_description_and_more'),
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='graph',
            field=models.ManyToManyField(related_name='business_types', to='graph.graph'),
        ),
    ]
