# Generated by Django 5.0.6 on 2024-06-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='file',
            field=models.FileField(upload_to='files/csv/'),
        ),
    ]
