# Generated by Django 5.0.6 on 2024-06-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0002_alter_uploaddata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcsv',
            name='year_month',
            field=models.CharField(max_length=128),
        ),
    ]
