# Generated by Django 5.0.6 on 2024-06-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0003_alter_restaurantcsv_year_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcsv',
            name='week',
            field=models.CharField(max_length=4),
        ),
    ]
