# Generated by Django 5.0.6 on 2024-06-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0004_alter_restaurantcsv_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcsv',
            name='min_order_datetime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='restaurantcsv',
            name='week_ending_mon_sun_dt',
            field=models.DateField(),
        ),
    ]
