# Generated by Django 5.0.6 on 2024-06-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0005_alter_restaurantcsv_min_order_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcsv',
            name='kpi',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='restaurantcsv',
            name='menu_category',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='restaurantcsv',
            name='menu_group',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='restaurantcsv',
            name='menu_item',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='restaurantcsv',
            name='month_nm',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='restaurantcsv',
            name='quarter',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='restaurantcsv',
            name='week',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='restaurantcsv',
            name='year',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='restaurantcsv',
            name='year_month',
            field=models.CharField(max_length=256),
        ),
    ]
