# Generated by Django 5.0.6 on 2024-06-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0002_remove_businessprofile_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='BusinessType',
        ),
    ]
