# Generated by Django 5.0.6 on 2024-06-12 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0003_alter_businessprofile_business_type_and_more'),
        ('business_type', '0002_businesstype_kpi'),
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='kpi',
            field=models.ManyToManyField(related_name='business_profiles', to='kpi.kpi'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_type.businesstype'),
        ),
    ]
