# Generated by Django 5.0.6 on 2024-06-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0004_businessprofile_kpi_and_more'),
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='graph',
            field=models.ManyToManyField(related_name='business_profiles', to='graph.graph'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
